_R='media_player'
_Q='input_boolean'
_P='smooth'
_O='script'
_N='automation'
_M='volume_down'
_L='volume_up'
_K='cover'
_J='switch'
_I='interval'
_H='light'
_G='fade'
_F='step'
_E='is_lower'
_D='is_raise'
_C='number'
_B=True
_A=False
DOMAIN='buttons_machine'
LUTRON_EVENT='lutron_caseta_button_event'
CONF_DEVICE_SERIAL='device_serial'
CONF_DEVICE_NAME='device_name'
CONF_AREA_NAME='area_name'
CONF_KEYPAD_TYPE='keypad_type'
CONF_BUTTONS='buttons'
CONF_BUTTON_NUMBER='button_number'
CONF_BUTTON_LABEL='label'
CONF_ACTION_TYPE='action_type'
CONF_STOP_ON_TAP='stop_on_tap'
CONF_SCROLL_STEP='scroll_step'
CONF_WHEEL_DECOUPLED='wheel_decoupled'
CONF_MEDIA_COMMAND='media_command'
CONF_COVER_HOLD_MOVE='cover_hold_move'
CONF_BLOCK_OWN_TARGETS='own_targets'
MEDIA_COMMANDS={'play_pause':'media_play_pause','play':'media_play','pause':'media_pause','stop':'media_stop','next':'media_next_track','previous':'media_previous_track','mute':'volume_mute',_L:_L,_M:_M}
CONF_ACTION_TARGET='action_target'
CONF_ACTION_PARAMS='action_params'
CONF_LED_ENTITY='led_entity'
CONF_LED_INVERT='led_invert'
CONF_LED_MODE='led_mode'
CONF_LED_COLOR='led_color'
CONF_TARGET_BRIGHTNESS='target_brightness'
CONF_TARGET_COLOR_TEMP='target_color_temp'
CONF_ENTITY_SETTINGS='entity_settings'
LED_MODE_ROOM='room'
LED_MODE_PATHWAY='pathway'
LED_MODE_SCENE='scene'
LED_COLORS=['white','blue','green','red','magenta','yellow','cyan']
KEYPAD_SEETOUCH='seetouch'
KEYPAD_SEETOUCH_HYBRID='seetouch_hybrid'
KEYPAD_SUNNATA='sunnata'
KEYPAD_SUNNATA_HYBRID='sunnata_hybrid'
KEYPAD_ALISEE='alisee'
KEYPAD_PALLADIOM='palladiom'
KEYPAD_TABLETOP='tabletop'
KEYPAD_PICO='pico'
KEYPAD_AVIENA='aviena'
KEYPAD_BILRESA='bilresa'
KEYPAD_GENERIC='generic'
KEYPAD_TYPES=[KEYPAD_SEETOUCH,KEYPAD_SEETOUCH_HYBRID,KEYPAD_SUNNATA,KEYPAD_SUNNATA_HYBRID,KEYPAD_ALISEE,KEYPAD_PALLADIOM,KEYPAD_TABLETOP,KEYPAD_PICO,KEYPAD_AVIENA,KEYPAD_BILRESA,KEYPAD_GENERIC]
RAISE_LOWER_BUTTON_TYPES={'raise':[3,5,7,17,19],'lower':[4,6,8,18,20]}
ACTION_STATEFUL_SCENE='stateful_scene'
ACTION_HA_SCENE='ha_scene'
ACTION_AUTOMATION=_N
ACTION_SCRIPT=_O
ACTION_ENTITY_TOGGLE='entity_toggle'
ACTION_SINGLE_ACTION='single_action'
ACTION_COVER_CYCLE='cover_cycle'
ACTION_MEDIA_CONTROL='media_control'
ACTION_DIM_CYCLE='dim_cycle'
ACTION_LIGHT_CYCLE_DIM='light_cycle_dim'
ACTION_RAISE='raise'
ACTION_LOWER='lower'
ACTION_NONE='none'
ACTION_TYPES=[ACTION_STATEFUL_SCENE,ACTION_HA_SCENE,ACTION_AUTOMATION,ACTION_SCRIPT,ACTION_ENTITY_TOGGLE,ACTION_SINGLE_ACTION,ACTION_COVER_CYCLE,ACTION_MEDIA_CONTROL,ACTION_DIM_CYCLE,ACTION_LIGHT_CYCLE_DIM,ACTION_RAISE,ACTION_LOWER,ACTION_NONE]
DIM_CYCLE_MODES={'quick':{_F:10,_I:.25,_G:.25},_P:{_F:5,_I:.35,_G:.35},'paced':{_F:3,_I:.6,_G:.6}}
DIM_CYCLE_DEFAULT_MODE=_P
DIM_CYCLE_STEP_MIN,DIM_CYCLE_STEP_MAX=1,25
DIM_CYCLE_TIME_MIN,DIM_CYCLE_TIME_MAX=.1,2.
RAMP_AUTO='auto'
RAMP_NATIVE='native'
RAMP_FADE=_G
RAMP_CHUNK='chunk'
RAMP_STEP=_F
RAMP_NONE='none'
RAMP_MODES=[RAMP_AUTO,RAMP_NATIVE,RAMP_FADE,RAMP_CHUNK,RAMP_STEP,RAMP_NONE]
RAMP_MODE_LABELS={RAMP_AUTO:'Auto',RAMP_NATIVE:'Bridge ramp',RAMP_FADE:'Smooth fade',RAMP_CHUNK:'Chunked fade',RAMP_STEP:'Step from Ctrlable Pro',RAMP_NONE:'No live dim'}
ATTR_RAMP_TOPIC='ramp_topic'
ATTR_ACTIVE_SCENE='active_scene'
ATTR_LAST_ACTION='last_action'
ATTR_COVER_STATES='cover_states'
ATTR_LIGHT_DIM_STEPS='light_dim_steps'
DIM_CYCLE_LEVELS=[100,75,50,25]
COVER_STATE_OPEN='open'
COVER_STATE_STOP='stop'
COVER_STATE_CLOSE='close'
RAISE_LOWER_STEP=10
SENSOR_SUFFIX_STATUS='status'
SENSOR_SUFFIX_LAST_BTN='last_button'
ACTION_TYPE_LABELS={ACTION_STATEFUL_SCENE:'Stateful Scene',ACTION_HA_SCENE:'HA Scene',ACTION_AUTOMATION:'Automation',ACTION_SCRIPT:'Script',ACTION_ENTITY_TOGGLE:'Entity Toggle',ACTION_SINGLE_ACTION:'Single Action',ACTION_COVER_CYCLE:'Cover Cycle',ACTION_DIM_CYCLE:'Dim Cycle',ACTION_LIGHT_CYCLE_DIM:'Dim Sequence',ACTION_RAISE:'Raise',ACTION_LOWER:'Lower',ACTION_NONE:'None'}
ACTION_LABEL_TO_TYPE={B:A for(A,B)in ACTION_TYPE_LABELS.items()}
ACTION_TYPE_DOMAINS={ACTION_STATEFUL_SCENE:[_J],ACTION_HA_SCENE:['scene'],ACTION_AUTOMATION:[_N],ACTION_SCRIPT:[_O],ACTION_ENTITY_TOGGLE:[_H,_J,'fan',_Q,_R,_K],ACTION_SINGLE_ACTION:[_H,_J,'fan',_Q,_R,_K],ACTION_COVER_CYCLE:[_K],ACTION_DIM_CYCLE:[_H],ACTION_LIGHT_CYCLE_DIM:[_H],ACTION_RAISE:[],ACTION_LOWER:[],ACTION_NONE:[]}
MULTI_ENTITY_ACTIONS=frozenset({ACTION_ENTITY_TOGGLE,ACTION_SINGLE_ACTION,ACTION_COVER_CYCLE,ACTION_LIGHT_CYCLE_DIM})
ACTION_TYPES_NEEDING_ENTITY=frozenset(A for(A,B)in ACTION_TYPE_DOMAINS.items()if B)
KEYPAD_LAYOUTS={KEYPAD_SEETOUCH:(6,_B),KEYPAD_SEETOUCH_HYBRID:(5,_B),KEYPAD_SUNNATA:(4,_B),KEYPAD_SUNNATA_HYBRID:(3,_B),KEYPAD_ALISEE:(5,_A),KEYPAD_PALLADIOM:(5,_B),KEYPAD_TABLETOP:(10,_A),KEYPAD_PICO:(3,_A),KEYPAD_AVIENA:(8,_A),KEYPAD_BILRESA:(9,_A),KEYPAD_GENERIC:(6,_B)}
def get_button_list(keypad_type):
	A,C=KEYPAD_LAYOUTS.get(keypad_type,KEYPAD_LAYOUTS[KEYPAD_GENERIC]);B=[{_C:A,_D:_A,_E:_A}for A in range(1,A+1)]
	if C:B.append({_C:A+1,_D:_B,_E:_A});B.append({_C:A+2,_D:_A,_E:_B})
	return B
def get_button_layout(entry_data):
	C='button_numbers';A=entry_data
	if A.get(CONF_KEYPAD_TYPE)==KEYPAD_BILRESA:D=A.get(C)or list(range(1,10));return[{_C:A,_D:A%3==1,_E:A%3==2}for A in D]
	B=A.get(C)
	if B:E=A.get('raise_button');F=A.get('lower_button');return[{_C:A,_D:A==E,_E:A==F}for A in sorted(B)]
	return get_button_list(A.get(CONF_KEYPAD_TYPE,KEYPAD_GENERIC))