_M='media_player'
_L='input_boolean'
_K='switch'
_J='script'
_I='automation'
_H='cover'
_G='light'
_F='scene'
_E='is_lower'
_D='is_raise'
_C='number'
_B=False
_A=True
DOMAIN='buttons_machine'
LUTRON_EVENT='lutron_caseta_button_event'
CONF_DEVICE_SERIAL='device_serial'
CONF_DEVICE_NAME='device_name'
CONF_AREA_NAME='area_name'
CONF_KEYPAD_TYPE='keypad_type'
CONF_BUTTONS='buttons'
CONF_BUTTON_NUMBER='button_number'
CONF_BUTTON_LABEL='label'
CONF_ACTION_TYPE='action_type'
CONF_ACTION_TARGET='action_target'
CONF_ACTION_PARAMS='action_params'
CONF_LED_ENTITY='led_entity'
CONF_LED_INVERT='led_invert'
CONF_LED_MODE='led_mode'
CONF_TARGET_BRIGHTNESS='target_brightness'
CONF_TARGET_COLOR_TEMP='target_color_temp'
CONF_ENTITY_SETTINGS='entity_settings'
LED_MODE_ROOM='room'
LED_MODE_PATHWAY='pathway'
LED_MODE_SCENE=_F
KEYPAD_SEETOUCH='seetouch'
KEYPAD_SEETOUCH_HYBRID='seetouch_hybrid'
KEYPAD_SUNNATA='sunnata'
KEYPAD_SUNNATA_HYBRID='sunnata_hybrid'
KEYPAD_ALISEE='alisee'
KEYPAD_PALLADIOM='palladiom'
KEYPAD_TABLETOP='tabletop'
KEYPAD_PICO='pico'
KEYPAD_GENERIC='generic'
KEYPAD_TYPES=[KEYPAD_SEETOUCH,KEYPAD_SEETOUCH_HYBRID,KEYPAD_SUNNATA,KEYPAD_SUNNATA_HYBRID,KEYPAD_ALISEE,KEYPAD_PALLADIOM,KEYPAD_TABLETOP,KEYPAD_PICO,KEYPAD_GENERIC]
RAISE_LOWER_BUTTON_TYPES={'raise':[3,5,7,17,19],'lower':[4,6,8,18,20]}
ACTION_STATEFUL_SCENE='stateful_scene'
ACTION_HA_SCENE='ha_scene'
ACTION_AUTOMATION=_I
ACTION_SCRIPT=_J
ACTION_ENTITY_TOGGLE='entity_toggle'
ACTION_SINGLE_ACTION='single_action'
ACTION_COVER_CYCLE='cover_cycle'
ACTION_LIGHT_CYCLE_DIM='light_cycle_dim'
ACTION_RAISE='raise'
ACTION_LOWER='lower'
ACTION_NONE='none'
ACTION_TYPES=[ACTION_STATEFUL_SCENE,ACTION_HA_SCENE,ACTION_AUTOMATION,ACTION_SCRIPT,ACTION_ENTITY_TOGGLE,ACTION_SINGLE_ACTION,ACTION_COVER_CYCLE,ACTION_LIGHT_CYCLE_DIM,ACTION_RAISE,ACTION_LOWER,ACTION_NONE]
ATTR_ACTIVE_SCENE='active_scene'
ATTR_LAST_ACTION='last_action'
ATTR_COVER_STATES='cover_states'
ATTR_LIGHT_DIM_STEPS='light_dim_steps'
DIM_CYCLE_LEVELS=[100,75,50,25]
COVER_STATE_OPEN='open'
COVER_STATE_STOP='stop'
COVER_STATE_CLOSE='close'
RAISE_LOWER_STEP=10
SENSOR_SUFFIX_STATUS='status'
SENSOR_SUFFIX_LAST_BTN='last_button'
ACTION_TYPE_LABELS={ACTION_STATEFUL_SCENE:'Stateful Scene',ACTION_HA_SCENE:'HA Scene',ACTION_AUTOMATION:'Automation',ACTION_SCRIPT:'Script',ACTION_ENTITY_TOGGLE:'Entity Toggle',ACTION_SINGLE_ACTION:'Single Action',ACTION_COVER_CYCLE:'Cover Cycle',ACTION_LIGHT_CYCLE_DIM:'Dim Cycle',ACTION_RAISE:'Raise',ACTION_LOWER:'Lower',ACTION_NONE:'None'}
ACTION_LABEL_TO_TYPE={B:A for(A,B)in ACTION_TYPE_LABELS.items()}
ACTION_TYPE_DOMAINS={ACTION_STATEFUL_SCENE:[_F],ACTION_HA_SCENE:[_F],ACTION_AUTOMATION:[_I],ACTION_SCRIPT:[_J],ACTION_ENTITY_TOGGLE:[_G,_K,'fan',_L,_M,_H],ACTION_SINGLE_ACTION:[_G,_K,'fan',_L,_M,_H],ACTION_COVER_CYCLE:[_H],ACTION_LIGHT_CYCLE_DIM:[_G],ACTION_RAISE:[],ACTION_LOWER:[],ACTION_NONE:[]}
MULTI_ENTITY_ACTIONS=frozenset({ACTION_ENTITY_TOGGLE,ACTION_SINGLE_ACTION,ACTION_COVER_CYCLE,ACTION_LIGHT_CYCLE_DIM})
ACTION_TYPES_NEEDING_ENTITY=frozenset(A for(A,B)in ACTION_TYPE_DOMAINS.items()if B)
KEYPAD_LAYOUTS={KEYPAD_SEETOUCH:(6,_A),KEYPAD_SEETOUCH_HYBRID:(5,_A),KEYPAD_SUNNATA:(4,_A),KEYPAD_SUNNATA_HYBRID:(3,_A),KEYPAD_ALISEE:(5,_B),KEYPAD_PALLADIOM:(5,_A),KEYPAD_TABLETOP:(10,_B),KEYPAD_PICO:(3,_B),KEYPAD_GENERIC:(6,_A)}
def get_button_list(keypad_type):
	A,C=KEYPAD_LAYOUTS.get(keypad_type,KEYPAD_LAYOUTS[KEYPAD_GENERIC]);B=[{_C:A,_D:_B,_E:_B}for A in range(1,A+1)]
	if C:B.append({_C:A+1,_D:_A,_E:_B});B.append({_C:A+2,_D:_B,_E:_A})
	return B
def get_button_layout(entry_data):
	A=entry_data;B=A.get('button_numbers')
	if B:C=A.get('raise_button');D=A.get('lower_button');return[{_C:A,_D:A==C,_E:A==D}for A in sorted(B)]
	return get_button_list(A.get(CONF_KEYPAD_TYPE,KEYPAD_GENERIC))